"""
Prompt Templates for LLM Analysis

Provides structured prompts for technical analysis, risk assessment, and sentiment analysis.
"""

from .technical_analysis import (
    TECHNICAL_ANALYSIS_PROMPT,
    PATTERN_RECOGNITION_PROMPT,
    MOMENTUM_ANALYSIS_PROMPT,
)
from .risk_assessment import (
    RISK_ASSESSMENT_PROMPT,
    MARKET_CONDITION_PROMPT,
    VOLATILITY_ANALYSIS_PROMPT,
)
from .sentiment import (
    SENTIMENT_ANALYSIS_PROMPT,
    TREND_DIRECTION_PROMPT,
    MOMENTUM_SENTIMENT_PROMPT,
)

__all__ = [
    "TECHNICAL_ANALYSIS_PROMPT",
    "PATTERN_RECOGNITION_PROMPT",
    "MOMENTUM_ANALYSIS_PROMPT",
    "RISK_ASSESSMENT_PROMPT",
    "MARKET_CONDITION_PROMPT",
    "VOLATILITY_ANALYSIS_PROMPT",
    "SENTIMENT_ANALYSIS_PROMPT",
    "TREND_DIRECTION_PROMPT",
    "MOMENTUM_SENTIMENT_PROMPT",
]
